server:
  port: 8030
spring:
  application:
    name: config-server
  cloud:
    config:
      # 分支
      label: master
      server:
        git:
          # Git 地址
          uri: https://github.com/LOVELINESSLYT/LinZeCloudConfigServer/
          # 目录
          searchPaths: respo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/